version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ..:/workspaces/gorm-performance
    working_dir: /workspaces/gorm-performance
    ports:
      - 8080:8080
    depends_on:
      - mysql
    tty: true
    networks:
      - dev-net
  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
